### ISSUE TITLE
Error fetching GPU Data

### ISSUE THREAD

**Issue by LeBIIIa** [JamesSmith2/EthControl#2]
Hello! I have found that when I run ethmonitoring gpu info doesn`t appear, but when I run ethcontrol, it shows the GPU data, but in console there is the error which appear almost after each request.
Also in EthControl doesn't update GPU Data value but in iOS app it updates and show correct value.
It just like some instance has value NULL.

My rig is: 3xGTX1060 3GB
Nvidia drivers: 441.87
EthControl version: 0.0.20 build 1035 

![image](https://user-images.githubusercontent.com/20616353/74549094-b5db0400-4f57-11ea-9838-ab729ccd94dd.png)

![image](https://user-images.githubusercontent.com/20616353/74549599-97c1d380-4f58-11ea-86fd-c6e73626c640.png)

**Comment by JamesSmith2** [comment]
Hey,

This is related to Nvidia-smi not found error, it tries to find it from program files -> nvidia corp -> nvsmi, but seems never ones have custom location in system32, try finding nvidia-smi.exe from C drive and select manually for it.

**Comment by LeBIIIa** [comment]
It seems that I cannot find nvidia-smi.exe with EthControl in System32, but there are few in System32\DriverStore maybe diff driver version and I take the last by date, this problem dissapear.
Thanks.
