### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by maviyol** [JamesSmith2/EthControl#3]
After 10 hours of trouble-free operation, Ethcontrol no longer sends data to ethmonitoring.com and android app... But the miner (PhoenixMiner 5.5c) is still working within ethcontrol and sends data to the pool...

**Comment by JamesSmith2** [comment]
Is there any error displayed?

**Comment by maviyol** [comment]
No.. I just got a notification from the app on my phone about the offline rig. When i checked it, saw that it is still mining and there was no error.

**Comment by JamesSmith2** [comment]
Send me log.txt and debug.txt if exists to info@ethmonitoring.com, i'l try to understand from logs.

**Comment by maviyol** [comment]
Unfortunately not. I uninstalled the program and reinstalled it.  In case of repetition, I will send the documents you that want to your e-mail address. Thanks for your interest..
